namespace CatalogCars.Model.Database.AuxiliaryTypes
{
    public enum SortingOption
    {
        Default, 
        ByAscendingName,
        ByDescendingName,
        ByAscendingAutoClass,
        ByDescendingAutoClass, 
        ByAscendingBodyTypeGroupName, 
        ByDescendingBodyTypeGroupName,
        ByAscendingRegionName,
        ByDescendingRegionName,
        ByAscendingLocationAddress,
        ByDescendingLocationAddress,
        ByAscendingMarkName,
        ByDescendingMarkName,
        ByAscendingModelName,
        ByDescendingModelName,
        ByAscendingYearFrom,
        ByDescendingYearFrom,
        ByAscendingRegistrationDate,
        ByDescendingRegistrationDate,
        ByAscendingCreationDate,
        ByDescendingCreationDate,
        ByAscendingUpdateDate,
        ByDescendingUpdateDate,
        ByAscendingPrice,
        ByDescendingPrice,
        ByAscendingYear,
        ByDescendingYear,
        ByAscendingMileage,
        ByDescendingMileage
    }
}
